<?php

return [
    [
        'name' => 'wxappid',
        'title' => '小程序AppID',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '小程序Appid，仅Uniapp版本使用',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'wxappsecret',
        'title' => '小程序AppSecret',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '小程序AppSecret，仅Uniapp版本使用',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'app_id',
        'title' => 'APP的AppID',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '微信开放平台中应用的Appid，仅Uniapp版本使用',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'app_secret',
        'title' => 'APP的AppSecret',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '微信开放平台中应用的AppSecret，仅Uniapp版本使用',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'system_user_id',
        'title' => '平台会员ID',
        'type' => 'string',
        'content' => [],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '用于统计平台收入的会员ID',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sitename',
        'title' => '站点名称',
        'type' => 'string',
        'content' => [],
        'value' => '我的问答',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sitelogo',
        'title' => '站点Logo',
        'type' => 'image',
        'content' => [],
        'value' => '/uploads/20220727/d1d086425440e13a3420f2791900c4c0.png',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'title',
        'title' => '首页标题',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'keywords',
        'title' => '首页关键字',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'description',
        'title' => '首页描述',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'admin_user_ids',
        'title' => '前台管理员ID集合',
        'type' => 'string',
        'content' => [],
        'value' => '1',
        'rule' => '',
        'msg' => '',
        'tip' => '前台可以管理问题、文章或标签的会员ID集合',
        'ok' => '',
        'extend' => 'class="form-control selectpage" data-source="user/user/index" data-field="nickname" data-multiple="true"',
    ],
    [
        'name' => 'peeptype',
        'title' => '付费查看类型',
        'type' => 'radio',
        'content' => [
            'price' => '金额',
            'score' => '积分',
            'both' => '两者',
            'none' => '无',
        ],
        'value' => 'both',
        'rule' => 'required',
        'msg' => '',
        'tip' => '付费查看可设定的类型',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'peepprice',
        'title' => '付费查看金额区间',
        'type' => 'string',
        'content' => [],
        'value' => '0.1-10',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '用户只能将付费查看的金额设置在此区间',
        'extend' => '',
    ],
    [
        'name' => 'peeppricelist',
        'title' => '付费查看金额列表',
        'type' => 'array',
        'content' => [],
        'value' => [
            '￥1' => '1',
            '￥2' => '2',
            '￥5' => '5',
            '￥10' => '10',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'peepscore',
        'title' => '付费查看积分区间',
        'type' => 'string',
        'content' => [],
        'value' => '10-100',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '用户只能将付费查看的积分设置在此区间',
        'extend' => '',
    ],
    [
        'name' => 'peepscorelist',
        'title' => '付费查看积分列表',
        'type' => 'array',
        'content' => [],
        'value' => [
            '10积分' => '10',
            '20积分' => '20',
            '50积分' => '50',
            '100积分' => '100',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'peepanswerratio',
        'title' => '付费查看分成',
        'type' => 'string',
        'content' => [],
        'value' => '0.3:0.1:0.6',
        'rule' => 'required',
        'msg' => '',
        'tip' => '平台:提问者:回答者 <br>请保证三者相加为1',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'bestanswerratio',
        'title' => '最佳答案分成',
        'type' => 'string',
        'content' => [],
        'value' => '0.3:0.7',
        'rule' => 'required',
        'msg' => '',
        'tip' => '平台:回答者 <br>请保证两者相加为1',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'articleratio',
        'title' => '付费文章分成',
        'type' => 'string',
        'content' => [],
        'value' => '0.3:0.7',
        'rule' => 'required',
        'msg' => '',
        'tip' => '平台:文章作者 <br>请保证两者相加为1',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'inviteprice',
        'title' => '付费邀请赏金区间',
        'type' => 'string',
        'content' => [],
        'value' => '1-10',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '用户只能将付费邀请的赏金设置在此区间',
        'extend' => '',
    ],
    [
        'name' => 'postanswerlimittype',
        'title' => '发表评论限制方式',
        'type' => 'radio',
        'content' => [
            'single' => '只能发表一次',
            'multiple' => '可多次发表回答',
        ],
        'value' => 'single',
        'rule' => 'required',
        'msg' => '',
        'tip' => '在对问题发表回答时，数量的限制',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'score',
        'title' => '获取积分设置',
        'type' => 'array',
        'content' => [],
        'value' => [
            'postquestion' => 3,
            'postanswer' => 1,
            'postarticle' => 5,
            'bestanswer' => 10,
            'postcomment' => 0,
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '如果问题或评论被删除则会扣除相应的积分',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'scorecyclelimit',
        'title' => '积分周期限制',
        'type' => 'array',
        'content' => [],
        'value' => [
            [
                'type' => 'postquestion',
                'day' => 0,
                'month' => 0,
                'year' => 0,
            ],
            [
                'type' => 'postanswer',
                'day' => 0,
                'month' => 0,
                'year' => 0,
            ],
            [
                'type' => 'postarticle',
                'day' => 0,
                'month' => 0,
                'year' => 0,
            ],
            [
                'type' => 'bestanswer',
                'day' => 0,
                'month' => 0,
                'year' => 0,
            ],
            [
                'type' => 'postcomment',
                'day' => 0,
                'month' => 0,
                'year' => 0,
            ],
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '超过设定的积分后将无法继续获取积分,0表示不限制',
        'ok' => '积分获取周期最高限制',
        'extend' => '',
    ],
    [
        'name' => 'limitscore',
        'title' => '限定积分设置',
        'type' => 'array',
        'content' => [],
        'value' => [
            'postquestion' => 0,
            'postanswer' => 0,
            'postarticle' => 0,
            'postcomment' => 0,
            'peepsetting' => 100,
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '必须达到相应的积分限制条件后才可以操作,0表示不限制',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'default_question_image',
        'title' => '默认问题图片',
        'type' => 'image',
        'content' => [],
        'value' => '/assets/addons/ask/img/question.png',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'default_tag_image',
        'title' => '默认话题图片',
        'type' => 'image',
        'content' => [],
        'value' => '/assets/addons/ask/img/tag.png',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'default_block_image',
        'title' => '默认区块图片',
        'type' => 'image',
        'content' => [],
        'value' => '/assets/addons/ask/img/block.png',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'default_zone_image',
        'title' => '默认专区图片',
        'type' => 'image',
        'content' => [],
        'value' => '/assets/addons/ask/img/zone.png',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'default_category_image',
        'title' => '默认分类图片',
        'type' => 'image',
        'content' => [],
        'value' => '/assets/addons/ask/img/category.png',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'awardtype',
        'title' => '悬赏提问类型',
        'type' => 'radio',
        'content' => [
            'money' => '金额',
            'score' => '积分',
            'both' => '两者',
            'none' => '无',
        ],
        'value' => 'both',
        'rule' => 'required',
        'msg' => '',
        'tip' => '悬赏提问可设定的类型',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'pricelist',
        'title' => '悬赏金额列表',
        'type' => 'array',
        'content' => [],
        'value' => [
            '￥10' => '10',
            '￥20' => '20',
            '￥30' => '30',
            '￥50' => '50',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'appendpricelist',
        'title' => '追加悬赏金额列表',
        'type' => 'array',
        'content' => [],
        'value' => [
            '￥1' => '1',
            '￥5' => '5',
            '￥10' => '10',
            '￥20' => '20',
            '￥50' => '50',
            '￥100' => '100',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'minprice',
        'title' => '付费悬赏最低金额',
        'type' => 'number',
        'content' => [],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '如果设定为付费悬赏，最低的悬赏金额',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'maxprice',
        'title' => '付费悬赏最高金额',
        'type' => 'number',
        'content' => [],
        'value' => '1000',
        'rule' => 'required',
        'msg' => '',
        'tip' => '如果设定为付费悬赏，最高的悬赏金额',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'iscustomprice',
        'title' => '任意金额悬赏',
        'type' => 'radio',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '开启后将支持自定义积分',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'scorelist',
        'title' => '悬赏积分列表',
        'type' => 'array',
        'content' => [],
        'value' => [
            '5积分' => '5',
            '10积分' => '10',
            '20积分' => '20',
            '30积分' => '30',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'appendscorelist',
        'title' => '追加悬赏积分列表',
        'type' => 'array',
        'content' => [],
        'value' => [
            '5积分' => '5',
            '10积分' => '10',
            '20积分' => '20',
            '30积分' => '30',
            '50积分' => '50',
            '100积分' => '100',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'minscore',
        'title' => '付费悬赏最低积分',
        'type' => 'number',
        'content' => [],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '如果设定为付费悬赏，最低的悬赏积分',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'maxscore',
        'title' => '付费悬赏最高积分',
        'type' => 'number',
        'content' => [],
        'value' => '100',
        'rule' => 'required',
        'msg' => '',
        'tip' => '如果设定为付费悬赏，最高的悬赏积分',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'iscustomscore',
        'title' => '任意积分悬赏',
        'type' => 'radio',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '开启后将支持自定义积分',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'isanonymous',
        'title' => '会员匿名提问',
        'type' => 'radio',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '开启匿名提问后将不再展示作者信息',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'isprivate',
        'title' => '提问私有答案',
        'type' => 'radio',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '开启私有答案功能将只有提问者和管理员可以查看',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'adoptdays',
        'title' => '提问有效期(天)',
        'type' => 'number',
        'content' => [],
        'value' => '7',
        'rule' => 'required',
        'msg' => '',
        'tip' => '提问超过指定天数后话题将无法享受分成',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'isstillanswer',
        'title' => '是否允许采纳后回答',
        'type' => 'radio',
        'content' => [
            1 => '可以继续回答',
            0 => '不再允许回答',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '采纳最佳答案后是否允许继续回答',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'isarticlepaidcomment',
        'title' => '文章是否只允许付费后可评论',
        'type' => 'radio',
        'content' => [
            1 => '是',
            0 => '否',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '付费文章是否只允许付费后才可评论',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'ispaylogin',
        'title' => '支付是否需要登录',
        'type' => 'radio',
        'content' => [
            1 => '是',
            0 => '否',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '设定支付时是否需要登录',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'pagesize',
        'title' => '分页大小设置',
        'type' => 'array',
        'content' => [],
        'value' => [
            'question' => '10',
            'article' => '10',
            'answer' => '10',
            'comment' => '10',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '设定问题、文章、回答、评论的分页大小',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'pagesimple',
        'title' => '分页简洁模式',
        'type' => 'checkbox',
        'content' => [
            'question' => '问题列表',
            'article' => '文章列表',
        ],
        'value' => 'question,article',
        'rule' => '',
        'msg' => '',
        'tip' => '如果未勾选将启用数字分页模式,勾选则只有上下页',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'captchaparts',
        'title' => '开启验证码模块',
        'type' => 'checkbox',
        'content' => [
            'postquestion' => '发布问题',
            'postarticle' => '发布文章',
            'postanswer' => '发布答案',
            'postcomment' => '发布评论',
        ],
        'value' => 'postquestion,postarticle,postanswer,postcomment',
        'rule' => '',
        'msg' => '',
        'tip' => '开启验证码的功能模块',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'maxinvitelimit',
        'title' => '每日免费邀请次数上限',
        'type' => 'number',
        'content' => [],
        'value' => '10',
        'rule' => 'required',
        'msg' => '',
        'tip' => '每日免费邀请超过指定上限后将无法发送邀请',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'reportlimit',
        'title' => '举报次数阀值',
        'type' => 'number',
        'content' => [],
        'value' => '3',
        'rule' => 'required',
        'msg' => '',
        'tip' => '超过举报次数阀值后将关闭问题、文章或回答,并不可见',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'reportreasonlist',
        'title' => '举报原因列表',
        'type' => 'array',
        'content' => [],
        'value' => [
            1 => '色情低俗',
            '政治敏感',
            '违法暴力',
            '恐怖血腥',
            '非法贩卖',
            '仇恨言论',
            '打小广告',
            '其他',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '超过举报次数阀值后将关闭问题、文章或回答,并不可见',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'isaudit',
        'title' => '内容审核',
        'type' => 'radio',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '开启内容审核后，违法或广告内容都将发布失败',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'audittype',
        'title' => '审核方式',
        'type' => 'radio',
        'content' => [
            'local' => '本地',
            'baiduyun' => '百度云',
        ],
        'value' => 'local',
        'rule' => 'required',
        'msg' => '',
        'tip' => '如果启用百度云，请输入百度云AI平台应用的AK和SK',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'nlptype',
        'title' => '分词方式',
        'type' => 'radio',
        'content' => [
            'local' => '本地',
            'baiduyun' => '百度云',
        ],
        'value' => 'local',
        'rule' => 'required',
        'msg' => '',
        'tip' => '如果启用百度云，请输入百度云AI平台应用的AK和SK',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'aip_appid',
        'title' => '百度AI平台应用Appid',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '百度云AI开放平台应用AppId',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'aip_apikey',
        'title' => '百度AI平台应用Apikey',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '百度云AI开放平台应用ApiKey',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'aip_secretkey',
        'title' => '百度AI平台应用Secretkey',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '百度云AI开放平台应用Secretkey',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'apikey',
        'title' => 'ApiKey密钥',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '用于调用API接口时写入数据权限控制<br>可以为空',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'autolinks',
        'title' => '关键字链接',
        'type' => 'array',
        'content' => [],
        'value' => [],
        'rule' => 'required',
        'msg' => '',
        'tip' => '对应的关键字将会自动加上链接',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'loadmode',
        'title' => '列表页加载模式',
        'type' => 'radio',
        'content' => [
            'infinite' => '无限加载模式',
            'paging' => '分页加载模式',
        ],
        'value' => 'infinite',
        'rule' => 'required',
        'msg' => '',
        'tip' => '问题列表和文章列表的加载模式(仅PC)',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'commentlistmode',
        'title' => '答案回复列表模式',
        'type' => 'radio',
        'content' => [
            'expanded' => '展开',
            'collapsed' => '折叠',
        ],
        'value' => 'expanded',
        'rule' => 'required',
        'msg' => '',
        'tip' => '答案的回复展现方式',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'emailnotice',
        'title' => '邮件通知',
        'type' => 'checkbox',
        'content' => [
            'firstanswer' => '第一个回答',
            'secondaryanswer' => '第2~N个回答',
            'message' => '收到私信',
            'adoptanswer' => '采纳答案',
            'ceritification' => '专家认证',
            'thanks' => '收到打赏(感谢)',
            'invite' => '收到邀请(普通)',
            'priceinvite' => '收到邀请(付费)',
        ],
        'value' => 'firstanswer,message,adoptanswer,ceritification,thanks,priceinvite',
        'rule' => 'required',
        'msg' => '',
        'tip' => '是否开启邮件消息通知',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'sendemailmode',
        'title' => '邮件发送模式',
        'type' => 'radio',
        'content' => [
            'queue' => '采用队列异步发送(速度快,需配置)',
            'phpmailer' => '采用PHPEmail同步发送(速度慢)',
        ],
        'value' => 'phpmailer',
        'rule' => 'required',
        'msg' => '',
        'tip' => '如果采用异步队列发送，请务必安装好Redis和think-queue，并配置启用队列服务',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'searchtype',
        'title' => '搜索方式',
        'type' => 'radio',
        'content' => [
            'local' => '本地搜索，采用Like(无需配置,效率低)',
            'xunsearch' => '采用Xunsearch全文搜索(需安装插件+配置)',
        ],
        'value' => 'local',
        'rule' => 'required',
        'msg' => '',
        'tip' => '如果启用Xunsearch全文搜索，需安装Xunsearch插件并配置Xunsearch服务端',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'baidupush',
        'title' => '百度熊掌号+百度站长推送',
        'type' => 'radio',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '如果开启百度熊掌+百度站长推送，将在问题和文章发布时自动进行推送',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'editormode',
        'title' => '编辑器模式',
        'type' => 'radio',
        'content' => [
            'normal' => '可视化编辑器',
            'markdown' => 'Markdown编辑器',
        ],
        'value' => 'normal',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'uploadparts',
        'title' => '上传模块',
        'type' => 'checkbox',
        'content' => [
            'image' => '图片',
            'file' => '附件',
        ],
        'value' => 'image',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'domain',
        'title' => '绑定二级域名前缀',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'rewrite',
        'title' => '伪静态',
        'type' => 'array',
        'content' => [],
        'value' => [
            'index/index' => '/ask/$',
            'tag/index' => '/ask/tags',
            'tag/show' => '/ask/tag/[:id]',
            'question/index' => '/ask/questions',
            'question/show' => '/ask/question/[:id]',
            'article/index' => '/ask/articles',
            'article/show' => '/ask/article/[:id]',
            'user/index' => '/u/[:id]$',
            'user/dispatch' => '/u/[:id]/[:dispatch]$',
            'expert/index' => '/ask/experts$',
            'search/index' => '/ask/search',
            'zone/index' => '/ask/zones',
            'zone/show' => '/ask/zone/[:diyname]',
        ],
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'debug',
        'title' => '问答调试模式',
        'type' => 'radio',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value' => '0',
        'rule' => 'required',
        'msg' => '',
        'tip' => '开启问答调试模式后,前台将加载无压缩的静态资源',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'default_article_image',
        'title' => '默认文章图片',
        'type' => 'image',
        'content' => [],
        'value' => '/assets/addons/ask/img/article.png',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'cachelifetime',
        'title' => '缓存默认时长',
        'type' => 'string',
        'content' => [],
        'value' => 'true',
        'rule' => 'required',
        'msg' => '',
        'tip' => '0表示不缓存,具体数字表示缓存时长,true表示永久缓存',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'urlsuffix',
        'title' => 'URL后缀',
        'type' => 'string',
        'content' => [
            1 => '开启',
            0 => '关闭',
        ],
        'value' => 'html',
        'rule' => '',
        'msg' => '如果不需要后缀可以设置为空',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'redirecturl',
        'title' => '外部链接中转链接',
        'type' => 'string',
        'content' => [],
        'value' => 'http://www.fa.com/addons/ask/go?url={url}',
        'rule' => '',
        'msg' => '问答中的链接将会被替换,其中{url}是替换的链接',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'allowdomainlist',
        'title' => '资源域名白名单',
        'type' => 'text',
        'content' => [],
        'value' => '*',
        'rule' => '',
        'msg' => '不要包含http://,一行一个域名,*表示全部',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
